// src/routes/blog/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	export let data: PageData;
	const { posts } = data;
</script>

<svelte:head>
	<title>blog posts</title>
	<meta name="description" content="a collection of all blog posts i've made so far" />
</svelte:head>

<h2>all posts</h2>
<ul>
	{#each posts as post}
		<li>
			<a class="hover:font-bold" href={post.path}>
				> {post.meta.title} | {post.meta.date}
			</a>
		</li>
	{/each}
</ul>

// app/routes/blog.tsx
import type { MetaFunction } from "@remix-run/cloudflare";

export const meta: MetaFunction = () => {
  return [
    { title: "blog posts" },
    {
      name: "description",
      content: "all of my blog posts, sorted nicely",
    },
  ];
};

// TODO: BLOG POSTS!
export default function Index() {
  return (
    <div>
      <h1>blog posts</h1>
      <ul>
        <li>post 1</li>
        <li>post 2</li>
      </ul>
    </div>
  );
}
